"use client";

import { FormEvent, useState } from "react";

const areas = [
  ["01", "Derecho inmobiliario", "Acompañamiento integral en operaciones, contratos, sucesiones y conflictos vinculados a inmuebles."],
  ["02", "Derecho civil", "Estrategias claras para resguardar sus derechos, con atención personalizada en cada etapa."],
  ["03", "Derecho laboral", "Asesoramiento preventivo y representación sólida para trabajadores y empresas."],
  ["04", "Derecho de familia", "Una mirada humana y resolutiva frente a los asuntos que más importan."],
];

const posts = [
  ["Guía legal", "Qué revisar antes de firmar un contrato de alquiler", "12 Jun 2026"],
  ["Actualidad", "Alquileres temporarios: obligaciones y oportunidades para propietarios", "28 May 2026"],
  ["Consejos", "Cómo proteger su patrimonio al realizar una operación inmobiliaria", "06 May 2026"],
];

function Arrow() { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" className="h-5 w-5"><path d="M5 12h14M13 6l6 6-6 6" /></svg>; }
function Scale() { return <svg viewBox="0 0 56 56" fill="none" stroke="currentColor" strokeWidth="1.4" className="h-9 w-9"><path d="M28 8v35m-14 0h28M17 16l-9 15h18l-9-15Zm22 0-9 15h18l-9-15Z"/><circle cx="28" cy="8" r="2"/></svg>; }

export default function Home() {
  const [open, setOpen] = useState(false);
  const [sent, setSent] = useState(false);
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); };
  const nav = ["El estudio", "Áreas de práctica", "Alquileres temporarios", "Publicaciones", "Contacto"];
  return <main className="overflow-hidden">
    <header className="absolute inset-x-0 top-0 z-20 text-white">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
        <a href="#inicio" className="leading-none"><span className="font-display text-2xl tracking-wide">Víctor Ibañez</span><span className="mt-1 block text-[9px] uppercase tracking-[.28em] text-[#d6bd91]">Estudio Jurídico</span></a>
        <nav className="hidden items-center gap-7 text-xs font-medium lg:flex">{nav.map(x => <a key={x} href={`#${x.toLowerCase().replaceAll(" ", "-")}`} className="hover:text-[#d6bd91] transition-colors">{x}</a>)}</nav>
        <a href="#contacto" className="hidden border border-[#d6bd91] px-4 py-2 text-xs font-semibold text-[#f5e7cb] transition hover:bg-[#d6bd91] hover:text-navy lg:block">Solicitar consulta</a>
        <button aria-label="Abrir menú" onClick={() => setOpen(!open)} className="grid h-9 w-9 place-items-center border border-white/40 lg:hidden"><span className="text-xl">{open ? "×" : "☰"}</span></button>
      </div>
      {open && <div className="border-t border-white/15 bg-navy px-6 py-5 lg:hidden">{nav.map(x => <a onClick={() => setOpen(false)} key={x} href={`#${x.toLowerCase().replaceAll(" ", "-")}`} className="block py-3 text-sm">{x}</a>)}</div>}
    </header>

    <section id="inicio" className="hero-pattern relative min-h-[760px] text-white">
      <div className="mx-auto flex min-h-[760px] max-w-7xl items-center px-6 pt-28 lg:px-10">
        <div className="max-w-3xl"><p className="mb-6 text-xs font-medium uppercase tracking-[.22em] text-[#d6bd91]">Córdoba · Argentina</p><h1 className="font-display text-5xl leading-[.95] sm:text-6xl lg:text-[5.5rem]">Defendemos lo que<br/><em className="font-normal text-[#e3c78f]">más le importa.</em></h1><p className="mt-8 max-w-xl text-base leading-7 text-white/75">Asesoramiento jurídico estratégico, humano y cercano para tomar decisiones con confianza.</p><div className="mt-10 flex flex-wrap gap-4"><a href="#contacto" className="inline-flex items-center gap-3 bg-gold px-6 py-3.5 text-sm font-semibold text-navy transition hover:bg-[#e3c78f]">Solicitar una consulta <Arrow/></a><a href="#áreas-de-práctica" className="inline-flex items-center gap-3 px-4 py-3.5 text-sm font-medium text-white hover:text-[#e3c78f]">Conocer el estudio <span className="text-xl">↓</span></a></div></div>
      </div>
      <div className="absolute bottom-0 left-6 right-6 mx-auto grid max-w-7xl grid-cols-2 border-t border-white/20 text-center sm:grid-cols-4 lg:left-10 lg:right-10">{[["+12", "años de trayectoria"], ["400+", "consultas resueltas"], ["4", "áreas de práctica"], ["100%", "atención personalizada"]].map(([n,t]) => <div key={t} className="border-r border-white/20 px-2 py-6 last:border-0"><strong className="font-display text-3xl text-[#e3c78f]">{n}</strong><span className="mt-1 block text-[10px] uppercase tracking-wider text-white/55">{t}</span></div>)}</div>
    </section>

    <section id="el-estudio" className="bg-sand py-24 lg:py-32"><div className="mx-auto grid max-w-7xl gap-16 px-6 lg:grid-cols-[.85fr_1.15fr] lg:px-10"><div><p className="eyebrow">El estudio</p><h2 className="mt-5 font-display text-5xl leading-none text-navy">El derecho, con una mirada <em className="font-normal text-[#a88046]">cercana.</em></h2></div><div className="max-w-2xl"><p className="text-xl leading-9 text-slate-600">Creemos que un buen asesoramiento no se mide solo por el resultado: también se construye con escucha, claridad y compromiso.</p><p className="mt-6 leading-7 text-slate-500">En Estudio Jurídico Víctor Ibañez combinamos experiencia técnica y una atención realmente personal. Cada caso recibe una estrategia pensada para sus necesidades, desde la primera consulta hasta su resolución.</p><a href="#contacto" className="line-link mt-8 inline-flex items-center gap-3 text-sm font-semibold text-navy">Conozca nuestra forma de trabajar <Arrow/></a></div></div></section>

    <section id="áreas-de-práctica" className="bg-white py-24 lg:py-32"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="mb-14 flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Especialidades</p><h2 className="mt-5 font-display text-5xl text-navy">Áreas de práctica</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">Respuestas concretas para situaciones complejas.</p></div><div className="grid gap-px bg-slate-200 md:grid-cols-2">{areas.map(([n,title,text]) => <article key={n} className="card-hover group bg-white p-8 lg:p-10"><span className="font-display text-2xl text-gold">{n}</span><div className="mt-14 flex items-start justify-between gap-5"><div><h3 className="font-display text-3xl text-navy">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-slate-500">{text}</p></div><span className="mt-1 text-gold transition-transform group-hover:translate-x-1"><Arrow/></span></div></article>)}</div></div></section>

    <section id="alquileres-temporarios" className="bg-navy py-24 text-white lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2 lg:px-10"><div><p className="eyebrow text-[#d6bd91]">Para propietarios</p><h2 className="mt-5 font-display text-5xl leading-none">Su propiedad, <em className="font-normal text-[#e3c78f]">bien administrada.</em></h2><p className="mt-7 max-w-lg leading-7 text-white/65">Brindamos acompañamiento jurídico y gestión especializada para propietarios que eligen el alquiler temporario como una inversión inteligente.</p><a href="#contacto" className="mt-9 inline-flex items-center gap-3 border border-[#d6bd91] px-5 py-3 text-sm font-semibold text-[#f5e7cb] transition hover:bg-[#d6bd91] hover:text-navy">Quiero conocer el servicio <Arrow/></a></div><div className="grid grid-cols-2 gap-4"><div className="border border-white/15 p-6"><span className="text-2xl text-[#e3c78f]">01</span><h3 className="mt-8 font-display text-2xl">Contratos claros</h3><p className="mt-3 text-sm leading-6 text-white/55">Marco legal y condiciones transparentes.</p></div><div className="mt-8 border border-white/15 p-6"><span className="text-2xl text-[#e3c78f]">02</span><h3 className="mt-8 font-display text-2xl">Gestión integral</h3><p className="mt-3 text-sm leading-6 text-white/55">Coordinación y seguimiento de su propiedad.</p></div><div className="border border-white/15 p-6"><span className="text-2xl text-[#e3c78f]">03</span><h3 className="mt-8 font-display text-2xl">Respaldo jurídico</h3><p className="mt-3 text-sm leading-6 text-white/55">Decisiones informadas y protegidas.</p></div><div className="mt-8 border border-white/15 p-6"><span className="text-2xl text-[#e3c78f]">04</span><h3 className="mt-8 font-display text-2xl">Más rentabilidad</h3><p className="mt-3 text-sm leading-6 text-white/55">Una alternativa simple para su inversión.</p></div></div></div></section>

    <section id="publicaciones" className="bg-sand py-24 lg:py-32"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="flex items-end justify-between"><div><p className="eyebrow">Recursos</p><h2 className="mt-5 font-display text-5xl text-navy">Publicaciones</h2></div><a href="#contacto" className="line-link hidden text-sm font-semibold sm:block">Ver todas</a></div><div className="mt-12 grid gap-6 md:grid-cols-3">{posts.map(([tag,title,date]) => <article key={title} className="card-hover flex min-h-72 flex-col bg-white p-7"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[#a88046]">{tag}</p><h3 className="mt-5 font-display text-3xl leading-8 text-navy">{title}</h3><div className="mt-auto flex items-center justify-between pt-6 text-xs text-slate-400"><time>{date}</time><span className="text-gold"><Arrow/></span></div></article>)}</div></div></section>

    <section id="contacto" className="bg-white py-24 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><Scale/><p className="eyebrow mt-8">Contacto</p><h2 className="mt-5 font-display text-5xl leading-none text-navy">Hablemos de<br/>su <em className="font-normal text-[#a88046]">caso.</em></h2><p className="mt-7 max-w-sm leading-7 text-slate-500">Complete el formulario y nos comunicaremos con usted a la brevedad.</p><div className="mt-10 space-y-3 text-sm text-slate-600"><p>📍 Córdoba, Argentina</p><p>✉ estudio@victoribanez.com.ar</p><p>◷ Lun. a Vie. · 9 a 18 h</p></div></div><form onSubmit={handleSubmit} className="grid gap-5 rounded-sm bg-sand p-7 sm:grid-cols-2 lg:p-10">{sent ? <div className="col-span-full py-16 text-center"><p className="font-display text-4xl text-navy">Gracias por contactarnos.</p><p className="mt-3 text-slate-500">Recibimos su consulta y responderemos pronto.</p></div> : <><label className="text-sm text-slate-600">Nombre y apellido<input required className="mt-2 w-full border-b border-slate-300 bg-transparent py-3 outline-none focus:border-gold" /></label><label className="text-sm text-slate-600">Teléfono<input required type="tel" className="mt-2 w-full border-b border-slate-300 bg-transparent py-3 outline-none focus:border-gold" /></label><label className="text-sm text-slate-600 sm:col-span-2">Correo electrónico<input required type="email" className="mt-2 w-full border-b border-slate-300 bg-transparent py-3 outline-none focus:border-gold" /></label><label className="text-sm text-slate-600 sm:col-span-2">¿En qué podemos ayudarlo?<textarea required rows={4} className="mt-2 w-full resize-none border-b border-slate-300 bg-transparent py-3 outline-none focus:border-gold" /></label><button className="mt-3 inline-flex w-fit items-center gap-3 bg-navy px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-[#143f5b] sm:col-span-2">Enviar consulta <Arrow/></button></>}</form></div></section>

    <footer className="bg-navy px-6 py-12 text-white lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-10 sm:flex-row"><div><p className="font-display text-2xl">Víctor Ibañez</p><p className="mt-1 text-[9px] uppercase tracking-[.28em] text-[#d6bd91]">Estudio Jurídico</p></div><div className="text-sm text-white/55"><p>Asesoramiento jurídico con compromiso.</p><p className="mt-2">© {new Date().getFullYear()} Estudio Jurídico Víctor Ibañez.</p></div><div className="flex gap-5 text-sm text-[#e3c78f]"><a href="#">Instagram</a><a href="#">LinkedIn</a></div></div></footer>
    <a href="https://wa.me/5490000000000?text=Hola%2C%20quisiera%20realizar%20una%20consulta." target="_blank" rel="noreferrer" aria-label="Contactar por WhatsApp" className="fixed bottom-6 right-6 z-30 grid h-14 w-14 place-items-center rounded-full bg-[#25d366] text-2xl text-white shadow-xl transition hover:scale-105">◔</a>
  </main>;
}
